name: xeus-r-wasm-build
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
  - conda-forge
dependencies:
  # Xeus-R
  - cmake
  - pkg-config
  - emscripten_emscripten-wasm32==3.1.73
  # Hera
  - r-base
  - r-rlang
  - r-jsonlite
  - r-base64enc
  - r-digest
  - r-fastmap
  - r-htmltools
  - r-cli
  - r-glue
  - r-vctrs
  # JupyterLite
  - jupyterlite-core
  - jupyter_server
  - jupyterlite-xeus
  # extra 
  - r-tidyverse
